apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2-app
  namespace: default
spec:
  selector:
    matchLabels:
      app: oauth2-app
  template:
    metadata:
      labels:
        app: oauth2-app
    spec:
      containers:
      - name: oauth2-app
        image: aabedraba/oauth-app:v0.1.0
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: oauth2-app-svc
  namespace: default
spec:
  selector:
    app: oauth2-app
  ports:
  - port: 3000
    targetPort: 3000
